### ISSUE TITLE
Slack or IRC channel

### ISSUE THREAD

**Issue by 6D65** [swiboe/swiboe#29]
Hi,

I guess the project would need a communication hub where people can discuss/propose ideas.
Slack might be more appropriate for this, with its various integrations.

Thanks.

**Comment by SShrike** [comment]
There is already a Gitter room, so what is the need for another chat room?

**Comment by 6D65** [comment]
There is no mention of it on the readme.md. Also, gitter si not that hip.

**Comment by SShrike** [comment]
There's a badge right at the top of the README, it looks exactly like this: [![Join the chat at https://gitter.im/swiboe/swiboe](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/swiboe/swiboe?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by 6D65** [comment]
Sorry, silly me. Didn't notice that one.

**Comment by SShrike** [comment]
Don't worry, we all have our dumb moments haha :)

**Comment by SirVer** [comment]
Just my 2c here: I have no experience with slack, but I only hear good things.

However, each communication channel adds overhead and needs people to care for. At this point in the life cycle of Swiboe, the gitter room seems sufficient - it is not even very active as of yet. Once the interest and community grows larger, other communication channels will be useful. But as of now I see adding more as a distraction that will bind resources and therefore impede rapid progress.

Agreed?

**Comment by 6D65** [comment]
Fine by me. Initially i just didn't notice the gitter chat icon, though it's most likely good enough for a start.
