### ISSUE TITLE
Ctrl-T list files does not work

### ISSUE THREAD

**Issue by cwahbong** [swiboe/swiboe#49]
When I am trying term_gui and press Ctrl-T, It always shows 0/0 matching (done).

list_rust_files is called on server, verified by println debugging.
But ListFiles::call is not called, also verified by println debugging.

To make sure we have a better debug environment, maybe I'll go working on #9 first.

**Comment by SirVer** [comment]
I have trouble compiling swiboe even right now due to aster - so I cannot repro :/

**Comment by cwahbong** [comment]
I've fixed it but build failing due to aster :(
