### ISSUE TITLE
What happened to Swiboe?

### ISSUE THREAD

**Issue by bcmyers** [swiboe/swiboe#65]
I enjoyed watching your YouTube videos, but it seems like both they and development on Swiboe has stopped.  Do you plan to pick it up again in the future?

**Comment by dpc** [comment]
AFAIK, the author had some personal life changes, and could not continue working on it.

**Comment by SirVer** [comment]
That is exactly what happened. My first child was born and I pulled out of open source as a hobby entirely to have more time for my family. Around the same time, [raphlinus](https://github.com/raphlinus) started [xi](https://github.com/google/xi-editor) which had similar design ideas as Swiboe. So it coincided that I did not have the energy for Swiboe anymore and that a better contender showed up.

Thanks for your interest in Swiboe!
