### ISSUE TITLE
Logger plugin

### ISSUE THREAD

**Issue by SirVer** [swiboe/swiboe#9]
printf debugging is often the fastest way to get information visible. With the terminal GUI that is harder than it needs to be - because whole terminal is owned by rustbox.

A simple solution is a plugin that connects to the server and registers a couple RPCs that can be used to output debug messages. Bonus points if that can also support timing events.

**Comment by cwahbong** [comment]
Maybe we can have a more generalized function, implemented as a logger plugin.

**Comment by cwahbong** [comment]
Tried to implement a very simple version. But I cannot simply call another rpc to swiboe server in client::rpc::server::Rpc::call.

**Comment by SirVer** [comment]
> Tried to implement a very simple version. But I cannot simply call another rpc to swiboe server in client::rpc::server::Rpc::call.

not sure what you mean by that. Why not?

**Comment by cwahbong** [comment]
At first I don't know there is a ThinClient, and it can be constructed by Client::clone().
Before I start to craft such class I found it by going through the implementation of buffer plugin. :)

**Comment by cwahbong** [comment]
Rfc and simple implementation is ready. Close this issue.
